import sys, os
from string import Template
import subprocess
sys.path.append(os.path.abspath('sphinxext'))

################################################################################
# NOTEBOOKS MANAGEMENT
################################################################################
# SETUP
nbdir  = "./notebooks/" # The notebooks that contains the notebooks.
rstdir = "./notebooks_rst/" # The directory where sphinx can store rst files.
template = Template(open("notebooks_index.template").read())
exclude_prefixes = ('_', '.')  # exclusion prefixes
file_suffixes = (".ipynb",)
title_levels = "+=~-_"

# DATA PROCESSING (whole section needs serious cleaning)
for dirpath, dirnames, filenames in os.walk(nbdir):
  dirnames[:] = [dirname
                 for dirname in dirnames
                 if not dirname.startswith(exclude_prefixes)]
  dirnames = sorted(dirnames)               
  filenames = [f for f in filenames if f.endswith(file_suffixes)]
  path_depth = len(dirpath.strip("./").strip("/").split("/")) 
  rst_path = dirpath.replace(nbdir, rstdir) 
  if rst_path.endswith("/") == False: rst_path += "/"
  if os.path.isdir(rst_path) == False: os.mkdir(rst_path)
  node = dirpath.strip("/").split("/")[-1]
  node_title = node.split("_")
  if len(node_title) > 1:
    node_title = " ".join(node_title[1:])
  else:
    node_title = node_title[0] 
  node_index = template.substitute(title = node_title.title(), 
                                   underline = 80*title_levels[path_depth])
  
  for f in filenames:
    nb = f[:-6]
    rst_back_path = "/".join([".."]*len(dirpath.strip(
                    "./").strip("/").split("/"))) + "/"
    nb_rst_path = ( rst_path.strip("/").strip("./")) +"/"+ nb +".rst"
    node_index += "   " + nb + "\n"
    
    os.system("jupyter-nbconvert {0}/{1}.ipynb --to rst --output {2}".format(
          dirpath, nb, rst_back_path+nb_rst_path))
    
    rst = ""
    rst += ".. Note::\n\n  This notebook can be downloaded here: "
    rst += ":download:`{2}.ipynb <{0}{1}/{2}.ipynb>` \n\n".format(
             rst_back_path, dirpath.strip("./"), nb)
    #rst += ".. contents::\n   :depth: 2\n"
    rst += open(nb_rst_path).read()
    open(nb_rst_path, "w").write(rst)
  for d in dirnames: 
    node_index += "   " + d + "/" + d + "\n"
  open(rst_path + node + ".rst", "w").write(node_index)              
                       
################################################################################


# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 
'sphinx.ext.mathjax',
'sphinx.ext.viewcode',
'sphinx.ext.doctest',
'matplotlib.sphinxext.only_directives',
'matplotlib.sphinxext.plot_directive',
#'sphinx_gallery.gen_gallery'
]

"""
# LC 2018/01/26
# SPHINX GALLERY CONFIG
sphinx_gallery_conf = {
# path to your examples scripts
'examples_dirs' : 'examples',
# path where to save gallery generated examples
'gallery_dirs'  : 'auto_examples',
'backreferences_dir': False}
"""

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u"Scientific Python: a collection of science oriented python examples"
copyright = u'2018, Ludovic Charleux, Emile Roux'
show_authors = True

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.0'
# The full version, including alpha/beta/rc tags.
#release = '1.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en_US'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = 'default'
html_theme = 'sphinx_rtd_theme'

#html_output_encoding = 'iso-8859-1'
html_output_encoding = 'utf-8'


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {'stickysidebar': True, 'sidebarwidth': 250}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = u'Scientific Python'
html_copy_source = True
html_show_sourcelink = True

